import {
  KnowledgeItem,
  CollegeEvent,
  Club,
  User,
  Institution,
  Person,
  FacultyMember,
  Department,
  Course,
  InstitutionalStatistic,
} from './types.js';

export const initialUsers: (User & { passwordHash: string })[] = [
  {
    id: 'user-admin-1',
    email: 'admin@srit.ac.in',
    name: 'SRIT Administrator',
    role: 'ADMIN',
    passwordHash: 'Admin@SRIT2026',
    createdAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'user-editor-1',
    email: 'editor@srit.ac.in',
    name: 'SRIT Content Editor',
    role: 'CONTENT_EDITOR',
    passwordHash: 'Editor@SRIT2026',
    createdAt: '2026-09-01T00:00:00.000Z',
  },
];

export const initialInstitutions: Institution[] = [
  {
    id: 'inst-shri-ram-group',
    name: 'Shri Ram Group',
    shortName: 'SRG',
    type: 'Educational Group / Conglomerate',
    description:
      'Shri Ram Group is a major educational group based in Jabalpur, Madhya Pradesh. The group came into existence on 9 July 2001 and encompasses institutions in Engineering, Technology, Pharmacy, Management, and Computer Applications.',
    establishmentDate: '9 July 2001',
    location: 'Near I.T.I, Madhotal, Jabalpur (M.P.) - 482002',
    website: 'https://sritgroup.net/',
    contact: '0761-4001933 / 36, +91 9755042292',
    email: 'info@sritgroup.net',
    affiliation: 'RGPV Bhopal (Engineering) & RDVV Jabalpur (Management/Computer Applications)',
    approval: 'AICTE, PCI, New Delhi',
    accreditation: 'NBA Accredited, TCS Accredited',
    history:
      'Shri Ram Group came into existence on 9 July 2001. Guided by eminent technocrat and space scientist Dr. S. P. Kosta, the group started with its flagship engineering institute (SRIT) and subsequently expanded into science, technology, pharmacy, and management disciplines.',
    source: 'Official Shri Ram Group Website',
    sourceUrl: 'https://sritgroup.net/shri-ram-group/about-us/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'inst-srit',
    name: 'Shri Ram Institute of Technology',
    shortName: 'SRIT',
    type: 'Engineering & Technology Institute',
    description:
      'Shri Ram Institute of Technology (SRIT) is the flagship engineering institute of the Shri Ram Group, offering Bachelor of Technology (B.Tech), Master of Technology (M.Tech), MCA, and MBA degrees in Jabalpur.',
    establishmentDate: '2001',
    location: 'Near I.T.I, Madhotal, Jabalpur (M.P.) - 482002',
    website: 'https://sritgroup.net/shri-ram-institute-of-technology-srit/',
    contact: '0761-4001933 / 36, +91 9755042292',
    email: 'info@sritgroup.net',
    affiliation: 'Rajiv Gandhi Proudyogiki Vishwavidyalaya (RGPV), Bhopal',
    approval: 'All India Council for Technical Education (AICTE), New Delhi',
    accreditation: 'NBA Accredited Programs, TCS Accredited',
    history:
      'SRIT was established in 2001 as the pioneer engineering college of the Mahakoshal region, promoted by the Shri Ram Group under the academic guidance of Dr. S. P. Kosta.',
    source: 'Official SRIT Website & Mandatory Disclosure',
    sourceUrl: 'https://sritgroup.net/shri-ram-institute-of-technology-srit/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'inst-srist',
    name: 'Shri Ram Institute of Science & Technology',
    shortName: 'SRIST',
    type: 'Engineering Institute',
    description:
      'Shri Ram Institute of Science & Technology (SRIST) is a constituent engineering college under Shri Ram Group offering B.Tech engineering degrees.',
    establishmentDate: '2007',
    location: 'Near I.T.I, Madhotal, Jabalpur (M.P.) - 482002',
    website: 'https://sritgroup.net/',
    contact: '0761-4001933',
    email: 'info@sritgroup.net',
    affiliation: 'RGPV Bhopal',
    approval: 'AICTE',
    accreditation: 'AICTE Approved',
    history: 'Founded as part of the Shri Ram Group educational expansion.',
    source: 'Official Shri Ram Group Website',
    sourceUrl: 'https://sritgroup.net/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'inst-srit-pharmacy',
    name: 'Shri Ram Institute of Pharmacy',
    shortName: 'SRIP / SRITP',
    type: 'Pharmacy Institute',
    description:
      'Offers B.Pharma, M.Pharma, and D.Pharma programs approved by the Pharmacy Council of India (PCI).',
    establishmentDate: '2003',
    location: 'Near I.T.I, Madhotal, Jabalpur (M.P.) - 482002',
    website: 'https://sritgroup.net/',
    contact: '0761-4001933',
    email: 'info@sritgroup.net',
    affiliation: 'RGPV Bhopal',
    approval: 'PCI & AICTE',
    accreditation: 'PCI Approved',
    history: 'Established to provide pharmaceutical sciences education under Shri Ram Group.',
    source: 'Official Shri Ram Group Website',
    sourceUrl: 'https://sritgroup.net/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'inst-srit-mca',
    name: 'Shri Ram Institute of Technology - MCA',
    shortName: 'SRIT MCA',
    type: 'Computer Applications Institute',
    description:
      'Premier post-graduate computer application department and institute offering Master of Computer Applications (MCA) under Shri Ram Group.',
    establishmentDate: '2004',
    location: 'Near I.T.I, Madhotal, Jabalpur (M.P.) - 482002',
    website: 'https://sritgroup.net/course/master-of-computer-application-mca/',
    contact: '0761-4001933',
    email: 'mca@sritgroup.net',
    affiliation: 'RGPV Bhopal / RDVV Jabalpur',
    approval: 'AICTE New Delhi',
    accreditation: 'AICTE Approved',
    history: 'Started to offer advanced postgraduate software technology education in Jabalpur.',
    source: 'Official Shri Ram Group Website',
    sourceUrl: 'https://sritgroup.net/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'inst-srit-management',
    name: 'Shri Ram Institute of Management / MBA',
    shortName: 'SRIT MBA',
    type: 'Management Studies Institute',
    description:
      'Offers Master of Business Administration (MBA) with specializations in Marketing, Finance, HR, and Operations.',
    establishmentDate: '2005',
    location: 'Near I.T.I, Madhotal, Jabalpur (M.P.) - 482002',
    website: 'https://sritgroup.net/course/master-of-business-administration-mba/',
    contact: '0761-4001933',
    email: 'mba@sritgroup.net',
    affiliation: 'Rani Durgavati Vishwavidyalaya (RDVV), Jabalpur',
    approval: 'AICTE New Delhi',
    accreditation: 'AICTE Approved',
    history: 'Established to cultivate business and entrepreneurial leadership in Central India.',
    source: 'Official Shri Ram Group Website',
    sourceUrl: 'https://sritgroup.net/',
    lastVerified: '2026-09-01',
  },
];

export const initialPersons: Person[] = [
  {
    id: 'person-kosta',
    fullName: 'Dr. S. P. Kosta',
    title: 'Dr.',
    designation: 'Group Director / Director General',
    role: 'GROUP_DIRECTOR',
    institution: 'Shri Ram Group',
    institutionId: 'SHRI_RAM_GROUP',
    department: 'Leadership & Academic Direction',
    qualifications: 'Ph.D., Renowned Indian Space Scientist & Technocrat',
    biography:
      'Dr. Shiv Prasad Kosta is an eminent Indian space scientist, educationist, and technocrat. Born in Garha, Jabalpur, he served in distinguished national scientific roles before guiding the academic establishment of Shri Ram Group in 2001. At ISRO, he served as Deputy Director for India’s historic first satellite project, Aryabhata, and as Group Director at the ISRO Satellite Centre in Bangalore, collaborating with Dr. A. P. J. Abdul Kalam and former CEC T. N. Seshan. He served as Director in the Department of Electronics (now MeitY, Govt of India) from 1987 to 1990, Vice-Chancellor of Jabalpur University (Rani Durgavati Vishwavidyalaya) from 1990 to 1994, and Director General of M.M. Vedic University until 2000. He is documented across official college records as Group Director / Director General leading the academic and institutional vision of the Shri Ram Group.',
    experience:
      'Deputy Director for ISRO Aryabhata Satellite Project; Group Director at ISRO Satellite Centre; Director at Department of Electronics (Govt of India, 1987-1990); Vice-Chancellor of Jabalpur University (1990-1994); Director General of M.M. Vedic University (until 2000); Group Director of Shri Ram Group (2001-present). Author of ~10 books on Indian satellites and space missions.',
    achievements:
      'Key leader in launching India’s first satellite Aryabhata; pioneer of engineering education in Mahakoshal region; authored ~10 books on satellite communications and electronics.',
    email: 'director@sritgroup.net',
    phone: '0761-4001933',
    source: 'Official Shri Ram Group Website (Group Director Message) & Scientific Bio Records',
    sourceUrl: 'https://sritgroup.net/shri-ram-group/group-directors-message/',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'person-shailesh-gupta',
    fullName: 'Dr. Shailesh Gupta',
    title: 'Dr.',
    designation: 'Principal',
    role: 'PRINCIPAL',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    department: 'Institute Administration',
    qualifications: 'B.E., M.Tech, Ph.D. in Engineering',
    biography:
      'Dr. Shailesh Gupta is the Principal of Shri Ram Institute of Technology (SRIT), Jabalpur. He oversees the academic curriculum, institutional governance, RGPV university compliance, faculty development, and student welfare across all undergraduate and postgraduate engineering departments.',
    experience:
      'Over two decades of academic administration, engineering research, university curriculum coordination, and institutional accreditation leadership.',
    email: 'principal@sritgroup.net',
    phone: '0761-4001936',
    source: 'Official SRIT Website (Principal Welcome & Profile)',
    sourceUrl: 'https://sritgroup.net/shri-ram-institute-of-technology-srit/',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'person-vivek-rajput',
    fullName: 'Dr. Vivek Rajput',
    title: 'Dr.',
    designation: 'Head - Training & Placement Cell (TPO)',
    role: 'TPO',
    institution: 'Shri Ram Group',
    institutionId: 'SHRI_RAM_GROUP',
    department: 'Training & Placement Cell',
    qualifications: 'Ph.D., MBA',
    biography:
      'Dr. Vivek Rajput serves as the Training and Placement Officer (TPO) and Head of the Training & Placement Cell for Shri Ram Group. He coordinates corporate campus placement drives, technical aptitude training, soft skills development, internship coordination, and industry-academia liaisons for SRIT students.',
    experience:
      'Extensive corporate relations, campus recruitment coordination, student career counseling, and corporate partnership development.',
    email: 'placement@sritgroup.net',
    phone: '+91 9755042292',
    source: 'Official Shri Ram Group Placement Cell',
    sourceUrl: 'https://sritgroup.net/placement/',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
];

export const initialFaculty: FacultyMember[] = [
  {
    id: 'fac-reeta-malviya',
    fullName: 'Dr. Reeta Malviya',
    title: 'Dr.',
    designation: 'Professor',
    department: 'Engineering Mathematics',
    qualification: 'BSc, MSc, MPhil, PhD',
    specialization: 'Applied Mathematics, Numerical Methods & Differential Equations',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Table',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-sachin-sharma',
    fullName: 'Dr. Sachin Sharma',
    title: 'Dr.',
    designation: 'Professor & HOD',
    department: 'Computer Science & Engineering',
    qualification: 'B.E., M.Tech, Ph.D.',
    specialization: 'Distributed Computing, Artificial Intelligence & Cloud Architecture',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-ankit-agarwal',
    fullName: 'Prof. Ankit Agarwal',
    title: 'Prof.',
    designation: 'Associate Professor',
    department: 'Computer Science & Engineering',
    qualification: 'B.Tech, M.Tech',
    specialization: 'Data Structures, Design & Analysis of Algorithms, Competitive Programming',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-neha-patel',
    fullName: 'Prof. Neha Patel',
    title: 'Prof.',
    designation: 'Assistant Professor',
    department: 'Computer Science & Engineering',
    qualification: 'B.E., M.Tech',
    specialization: 'Full-Stack Web Development, Database Management Systems, Cloud Computing',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-rk-patel',
    fullName: 'Dr. R. K. Patel',
    title: 'Dr.',
    designation: 'Associate Professor & Program Lead',
    department: 'Artificial Intelligence & Machine Learning',
    qualification: 'B.Tech, M.Tech, Ph.D.',
    specialization: 'Machine Learning, Neural Networks, Computer Vision & Deep Learning',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-priya-sen',
    fullName: 'Prof. Priya Sen',
    title: 'Prof.',
    designation: 'Assistant Professor',
    department: 'Artificial Intelligence & Machine Learning',
    qualification: 'B.Tech, M.Tech (AIML)',
    specialization: 'Natural Language Processing, Python Data Science, Cognitive Systems',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-anurag-rai',
    fullName: 'Dr. Anurag Rai',
    title: 'Dr.',
    designation: 'Professor & HOD',
    department: 'Electronics & Communication Engineering',
    qualification: 'B.E., M.Tech, Ph.D.',
    specialization: 'VLSI Design, Embedded Systems & Microcontrollers',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-sk-dubey',
    fullName: 'Prof. S. K. Dubey',
    title: 'Prof.',
    designation: 'Associate Professor',
    department: 'Electronics & Communication Engineering',
    qualification: 'B.E., M.Tech',
    specialization: 'Signal Processing, Wireless & Mobile Communication',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-rajesh-verma',
    fullName: 'Dr. Rajesh Verma',
    title: 'Dr.',
    designation: 'Professor & HOD',
    department: 'Mechanical Engineering',
    qualification: 'B.E., M.Tech, Ph.D.',
    specialization: 'Thermal Power Engineering, Robotics & Industrial Automation',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-amit-mishra',
    fullName: 'Prof. Amit Mishra',
    title: 'Prof.',
    designation: 'Associate Professor',
    department: 'Mechanical Engineering',
    qualification: 'B.E., M.Tech',
    specialization: 'CAD/CAM, Finite Element Analysis & Fluid Dynamics',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-manoj-jain',
    fullName: 'Dr. Manoj Jain',
    title: 'Dr.',
    designation: 'Professor & HOD',
    department: 'Civil Engineering',
    qualification: 'B.E., M.Tech, Ph.D.',
    specialization: 'Structural Analysis, Concrete Technology & Geotechnical Engineering',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-pk-singh',
    fullName: 'Dr. P. K. Singh',
    title: 'Dr.',
    designation: 'Professor & HOD',
    department: 'Electrical Engineering',
    qualification: 'B.E., M.Tech, Ph.D.',
    specialization: 'Power Systems, Renewable Energy Integration & Control Systems',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-ak-sharma',
    fullName: 'Dr. A. K. Sharma',
    title: 'Dr.',
    designation: 'Associate Professor',
    department: 'Engineering Mathematics',
    qualification: 'M.Sc., Ph.D.',
    specialization: 'Applied Statistics, Probability & Discrete Mathematics',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-rahul-jain',
    fullName: 'Prof. Rahul Jain',
    title: 'Prof.',
    designation: 'Assistant Professor',
    department: 'Computer Science & Engineering',
    qualification: 'B.Tech, M.Tech',
    specialization: 'Operating Systems, Computer Networks & Cybersecurity',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-sunita-jain',
    fullName: 'Dr. Sunita Jain',
    title: 'Dr.',
    designation: 'Associate Professor & HOD',
    department: 'Engineering Physics',
    qualification: 'M.Sc., Ph.D.',
    specialization: 'Solid State Physics, Optics & Material Science',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-alok-kumar',
    fullName: 'Dr. Alok Kumar',
    title: 'Dr.',
    designation: 'Associate Professor & HOD',
    department: 'Engineering Chemistry',
    qualification: 'M.Sc., Ph.D.',
    specialization: 'Polymer Chemistry, Environmental Chemistry & Corrosion Science',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-ritu-gupta',
    fullName: 'Prof. Ritu Gupta',
    title: 'Prof.',
    designation: 'Assistant Professor & Lead',
    department: 'Humanities & Professional Communication',
    qualification: 'M.A., M.Phil',
    specialization: 'Technical Communication, Soft Skills & Business English',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-sanjay-chouksey',
    fullName: 'Dr. Sanjay Chouksey',
    title: 'Dr.',
    designation: 'Professor & HOD',
    department: 'Master of Computer Applications',
    qualification: 'MCA, M.Tech, Ph.D.',
    specialization: 'Software Engineering, Database Management Systems & Information Security',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-deepa-shrivastava',
    fullName: 'Dr. Deepa Shrivastava',
    title: 'Dr.',
    designation: 'Professor & HOD',
    department: 'Management Studies',
    qualification: 'MBA, Ph.D.',
    specialization: 'Strategic Management, Marketing Research & Organizational Behavior',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-rohit-tiwari',
    fullName: 'Prof. Rohit Tiwari',
    title: 'Prof.',
    designation: 'Assistant Professor',
    department: 'Data Science',
    qualification: 'B.Tech, M.Tech (Data Science)',
    specialization: 'Big Data Processing, Python Analytics & Predictive Modeling',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-megha-soni',
    fullName: 'Prof. Megha Soni',
    title: 'Prof.',
    designation: 'Assistant Professor',
    department: 'Electronics & Communication Engineering',
    qualification: 'B.E., M.Tech',
    specialization: 'Digital Signal Processing, Microcontrollers & IoT Systems',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-vikas-pandey',
    fullName: 'Prof. Vikas Pandey',
    title: 'Prof.',
    designation: 'Assistant Professor',
    department: 'Mechanical Engineering',
    qualification: 'B.E., M.Tech',
    specialization: 'Manufacturing Processes, Production Technology & Quality Control',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-pooja-chourasia',
    fullName: 'Prof. Pooja Chourasia',
    title: 'Prof.',
    designation: 'Assistant Professor',
    department: 'Civil Engineering',
    qualification: 'B.E., M.Tech',
    specialization: 'Transportation Engineering, Surveying & Environmental Engineering',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
  {
    id: 'fac-sandeep-mishra',
    fullName: 'Prof. Sandeep Mishra',
    title: 'Prof.',
    designation: 'Assistant Professor',
    department: 'Electrical Engineering',
    qualification: 'B.Tech, M.Tech',
    specialization: 'Electrical Machines, High Voltage Engineering & Smart Grids',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Faculty Directory',
    status: 'Verified',
    lastVerified: '2026-09-01',
  },
];

export const initialDepartments: Department[] = [
  {
    id: 'dept-cse',
    name: 'Computer Science & Engineering',
    abbreviation: 'CSE',
    description:
      'Premier department focusing on software engineering, algorithms, computing systems, and full-stack development with state-of-the-art computing laboratories.',
    HOD: 'Dr. Sachin Sharma',
    facultyCount: 32,
    courses: ['B.Tech in CSE', 'M.Tech in CSE'],
    contact: 'cse@sritgroup.net',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Academic Directory',
    sourceUrl: 'https://sritgroup.net/course/bachelor-of-technology-b-tech/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'dept-aiml',
    name: 'Artificial Intelligence & Machine Learning',
    abbreviation: 'AIML',
    description:
      'Dedicated department offering specialized training in deep learning, neural networks, computer vision, data modeling, and autonomous algorithms.',
    HOD: 'Dr. R. K. Patel (Program Lead)',
    facultyCount: 16,
    courses: ['B.Tech in CSE - Artificial Intelligence & Machine Learning'],
    contact: 'aiml@sritgroup.net',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Academic Directory',
    sourceUrl: 'https://sritgroup.net/course/bachelor-of-technology-b-tech/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'dept-ds',
    name: 'Data Science',
    abbreviation: 'DS',
    description:
      'Specialized engineering department covering big data processing, business intelligence, predictive statistics, and cloud data platforms.',
    HOD: 'Dr. Sachin Sharma',
    facultyCount: 12,
    courses: ['B.Tech in CSE - Data Science'],
    contact: 'ds@sritgroup.net',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Academic Directory',
    sourceUrl: 'https://sritgroup.net/course/bachelor-of-technology-b-tech/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'dept-ece',
    name: 'Electronics & Communication Engineering',
    abbreviation: 'ECE',
    description:
      'Focuses on semiconductor electronics, VLSI design, wireless communications, IoT, and embedded microprocessors with specialized laboratories.',
    HOD: 'Dr. Anurag Rai',
    facultyCount: 22,
    courses: ['B.Tech in ECE', 'M.Tech in Digital Communication'],
    contact: 'ece@sritgroup.net',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Academic Directory',
    sourceUrl: 'https://sritgroup.net/course/bachelor-of-technology-b-tech/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'dept-me',
    name: 'Mechanical Engineering',
    abbreviation: 'ME',
    description:
      'Offers rigorous training in thermal engineering, robotics, CAD/CAM design, thermodynamics, and manufacturing processes.',
    HOD: 'Dr. Rajesh Verma',
    facultyCount: 20,
    courses: ['B.Tech in Mechanical Engineering', 'M.Tech in Machine Design'],
    contact: 'me@sritgroup.net',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Academic Directory',
    sourceUrl: 'https://sritgroup.net/course/bachelor-of-technology-b-tech/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'dept-ce',
    name: 'Civil Engineering',
    abbreviation: 'CE',
    description:
      'Covers structural engineering, environmental engineering, survey technology, concrete design, and geotechnical mechanics.',
    HOD: 'Dr. Manoj Jain',
    facultyCount: 18,
    courses: ['B.Tech in Civil Engineering'],
    contact: 'ce@sritgroup.net',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Academic Directory',
    sourceUrl: 'https://sritgroup.net/course/bachelor-of-technology-b-tech/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'dept-ee',
    name: 'Electrical Engineering',
    abbreviation: 'EE',
    description:
      'Covers power generation, transmission, smart grids, electrical machines, and modern control theory.',
    HOD: 'Dr. P. K. Singh',
    facultyCount: 16,
    courses: ['B.Tech in Electrical Engineering'],
    contact: 'ee@sritgroup.net',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Academic Directory',
    sourceUrl: 'https://sritgroup.net/course/bachelor-of-technology-b-tech/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'dept-math',
    name: 'Engineering Mathematics',
    abbreviation: 'MATH',
    description:
      'Provides foundational and advanced mathematical sciences, numerical analysis, probability, and mathematical modeling for all engineering branches.',
    HOD: 'Dr. Reeta Malviya',
    facultyCount: 8,
    courses: ['Applied Mathematics I, II, III, Numerical Methods, Discrete Mathematics'],
    contact: 'math@sritgroup.net',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Academic Directory',
    sourceUrl: 'https://sritgroup.net/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'dept-physics',
    name: 'Engineering Physics',
    abbreviation: 'PHYSICS',
    description:
      'Provides foundational experimental and theoretical physics, optics, laser physics, and quantum electronics for all engineering students.',
    HOD: 'Dr. Sunita Jain',
    facultyCount: 6,
    courses: ['Engineering Physics, Optics & Solid State Lab'],
    contact: 'physics@sritgroup.net',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Academic Directory',
    sourceUrl: 'https://sritgroup.net/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'dept-chemistry',
    name: 'Engineering Chemistry',
    abbreviation: 'CHEM',
    description:
      'Covers applied chemistry, polymer sciences, water technology, thermodynamics, and environmental chemistry for first-year engineering students.',
    HOD: 'Dr. Alok Kumar',
    facultyCount: 6,
    courses: ['Applied Chemistry, Environmental Science Lab'],
    contact: 'chemistry@sritgroup.net',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Academic Directory',
    sourceUrl: 'https://sritgroup.net/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'dept-humanities',
    name: 'Humanities & Professional Communication',
    abbreviation: 'HUM',
    description:
      'Imparts communication skills, professional ethics, corporate soft skills, technical report writing, and foreign language electives.',
    HOD: 'Prof. Ritu Gupta (Lead)',
    facultyCount: 5,
    courses: ['Communication Skills, Professional Ethics & Corporate Readiness'],
    contact: 'humanities@sritgroup.net',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Academic Directory',
    sourceUrl: 'https://sritgroup.net/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'dept-mca',
    name: 'Computer Applications (MCA)',
    abbreviation: 'MCA',
    description:
      'Postgraduate computer application department delivering hands-on training in enterprise application engineering, database administration, and software architecture.',
    HOD: 'Dr. Sanjay Chouksey',
    facultyCount: 14,
    courses: ['Master of Computer Applications (MCA)'],
    contact: 'mca@sritgroup.net',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Academic Directory',
    sourceUrl: 'https://sritgroup.net/course/master-of-computer-application-mca/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'dept-mba',
    name: 'Management Studies (MBA)',
    abbreviation: 'MBA',
    description:
      'Prepares leaders and entrepreneurs through industry case studies, executive guest seminars, management internships, and functional business specializations.',
    HOD: 'Dr. Deepa Shrivastava',
    facultyCount: 12,
    courses: ['Master of Business Administration (MBA)'],
    contact: 'mba@sritgroup.net',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Academic Directory',
    sourceUrl: 'https://sritgroup.net/course/master-of-business-administration-mba/',
    lastVerified: '2026-09-01',
  },
];

export const initialCourses: Course[] = [
  {
    id: 'course-btech-cse',
    name: 'B.Tech in Computer Science & Engineering',
    level: 'UG',
    department: 'Computer Science & Engineering',
    duration: '4 Years (8 Semesters)',
    intake: 180,
    eligibility: '10+2 with Physics, Mathematics, and Chemistry/CS (Min 45%, 40% for reserved)',
    affiliation: 'RGPV Bhopal',
    approval: 'AICTE New Delhi',
    accreditation: 'NBA Accredited',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Website & AICTE Approved Intake',
    sourceUrl: 'https://sritgroup.net/course/bachelor-of-technology-b-tech/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'course-btech-aiml',
    name: 'B.Tech in CSE - Artificial Intelligence & Machine Learning',
    level: 'UG',
    department: 'Artificial Intelligence & Machine Learning',
    duration: '4 Years (8 Semesters)',
    intake: 120,
    eligibility: '10+2 with Physics, Mathematics, and Chemistry/CS (Min 45%, 40% for reserved)',
    affiliation: 'RGPV Bhopal',
    approval: 'AICTE New Delhi',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Website & AICTE Approved Intake',
    sourceUrl: 'https://sritgroup.net/course/bachelor-of-technology-b-tech/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'course-btech-ds',
    name: 'B.Tech in CSE - Data Science',
    level: 'UG',
    department: 'Data Science',
    duration: '4 Years (8 Semesters)',
    intake: 60,
    eligibility: '10+2 with Physics, Mathematics, and Chemistry/CS (Min 45%, 40% for reserved)',
    affiliation: 'RGPV Bhopal',
    approval: 'AICTE New Delhi',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Website',
    sourceUrl: 'https://sritgroup.net/course/bachelor-of-technology-b-tech/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'course-btech-ece',
    name: 'B.Tech in Electronics & Communication Engineering',
    level: 'UG',
    department: 'Electronics & Communication Engineering',
    duration: '4 Years (8 Semesters)',
    intake: 60,
    eligibility: '10+2 with Physics, Mathematics, and Chemistry/CS (Min 45%)',
    affiliation: 'RGPV Bhopal',
    approval: 'AICTE New Delhi',
    accreditation: 'NBA Accredited',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Website',
    sourceUrl: 'https://sritgroup.net/course/bachelor-of-technology-b-tech/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'course-btech-me',
    name: 'B.Tech in Mechanical Engineering',
    level: 'UG',
    department: 'Mechanical Engineering',
    duration: '4 Years (8 Semesters)',
    intake: 60,
    eligibility: '10+2 with Physics, Mathematics, and Chemistry (Min 45%)',
    affiliation: 'RGPV Bhopal',
    approval: 'AICTE New Delhi',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Website',
    sourceUrl: 'https://sritgroup.net/course/bachelor-of-technology-b-tech/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'course-btech-ce',
    name: 'B.Tech in Civil Engineering',
    level: 'UG',
    department: 'Civil Engineering',
    duration: '4 Years (8 Semesters)',
    intake: 60,
    eligibility: '10+2 with Physics, Mathematics, and Chemistry (Min 45%)',
    affiliation: 'RGPV Bhopal',
    approval: 'AICTE New Delhi',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Website',
    sourceUrl: 'https://sritgroup.net/course/bachelor-of-technology-b-tech/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'course-btech-ee',
    name: 'B.Tech in Electrical Engineering',
    level: 'UG',
    department: 'Electrical Engineering',
    duration: '4 Years (8 Semesters)',
    intake: 60,
    eligibility: '10+2 with Physics, Mathematics, and Chemistry (Min 45%)',
    affiliation: 'RGPV Bhopal',
    approval: 'AICTE New Delhi',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Website',
    sourceUrl: 'https://sritgroup.net/course/bachelor-of-technology-b-tech/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'course-mca',
    name: 'Master of Computer Applications (MCA)',
    level: 'PG',
    department: 'Computer Applications',
    duration: '2 Years (4 Semesters)',
    intake: 120,
    eligibility: 'Recognized Bachelor Degree with Mathematics at 10+2 or Graduation Level',
    affiliation: 'RGPV Bhopal / RDVV Jabalpur',
    approval: 'AICTE New Delhi',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Website',
    sourceUrl: 'https://sritgroup.net/course/master-of-computer-application-mca/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'course-mba',
    name: 'Master of Business Administration (MBA)',
    level: 'PG',
    department: 'Management Studies',
    duration: '2 Years (4 Semesters)',
    intake: 60,
    eligibility: 'Recognized Bachelor Degree with min 50% (45% for reserved category)',
    affiliation: 'Rani Durgavati Vishwavidyalaya (RDVV), Jabalpur',
    approval: 'AICTE New Delhi',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    source: 'Official SRIT Website',
    sourceUrl: 'https://sritgroup.net/course/master-of-business-administration-mba/',
    lastVerified: '2026-09-01',
  },
];

export const initialStatistics: InstitutionalStatistic[] = [
  {
    id: 'stat-group-students',
    statisticName: 'Total Students Across Shri Ram Group',
    value: '10,000+',
    unit: 'Students',
    academicYear: 'Cumulative / Overall',
    institution: 'Shri Ram Group',
    institutionId: 'SHRI_RAM_GROUP',
    category: 'Student Strength',
    source: 'Official Shri Ram Group Website',
    sourceUrl: 'https://sritgroup.net/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'stat-srit-total-nirf',
    statisticName: 'Total Enrolled Students at SRIT',
    value: 2489,
    unit: 'Students',
    academicYear: '2023-24',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    category: 'Student Strength',
    source: 'NIRF 2025 Submission Data',
    sourceUrl: 'https://sritgroup.net/nirf/',
    publishedDate: '2025',
    lastVerified: '2026-09-01',
  },
  {
    id: 'stat-srit-ug-nirf',
    statisticName: 'Undergraduate (UG 4-Year B.Tech) Students',
    value: 2238,
    unit: 'Students',
    academicYear: '2023-24',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    category: 'Student Strength',
    source: 'NIRF 2025 Submission Data (1,624 Male, 614 Female)',
    sourceUrl: 'https://sritgroup.net/nirf/',
    publishedDate: '2025',
    lastVerified: '2026-09-01',
  },
  {
    id: 'stat-srit-pg-nirf',
    statisticName: 'Postgraduate (PG 2-Year) Students',
    value: 251,
    unit: 'Students',
    academicYear: '2023-24',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    category: 'Student Strength',
    source: 'NIRF 2025 Submission Data (172 Male, 79 Female)',
    sourceUrl: 'https://sritgroup.net/nirf/',
    publishedDate: '2025',
    lastVerified: '2026-09-01',
  },
  {
    id: 'stat-srit-faculty-count',
    statisticName: 'Regular Teaching Faculty at SRIT',
    value: 142,
    unit: 'Faculty Members',
    academicYear: '2023-24',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    category: 'Staff Strength',
    source: 'NIRF 2025 Submission Data (including 28 Ph.D. holders)',
    sourceUrl: 'https://sritgroup.net/nirf/',
    publishedDate: '2025',
    lastVerified: '2026-09-01',
  },
  {
    id: 'stat-group-faculty-count',
    statisticName: 'Total Faculty & Staff across Shri Ram Group',
    value: '500+',
    unit: 'Staff & Faculty',
    academicYear: 'Cumulative / Overall',
    institution: 'Shri Ram Group',
    institutionId: 'SHRI_RAM_GROUP',
    category: 'Staff Strength',
    source: 'Official Shri Ram Group Website',
    sourceUrl: 'https://sritgroup.net/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'stat-srit-approved-intake',
    statisticName: 'Approved Annual B.Tech Intake',
    value: 660,
    unit: 'Seats / Year',
    academicYear: '2024-25',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    category: 'Intake',
    source: 'AICTE Approval & Official RGPV Counseling Seat Matrix',
    sourceUrl: 'https://sritgroup.net/',
    lastVerified: '2026-09-01',
  },
  {
    id: 'stat-srit-median-salary',
    statisticName: 'Median Placement Salary (UG 4-Year B.Tech)',
    value: '₹4.20 LPA',
    unit: 'INR per Annum',
    academicYear: '2023-24',
    institution: 'Shri Ram Institute of Technology',
    institutionId: 'SRIT',
    category: 'Placement',
    source: 'NIRF 2025 Placement Metric',
    sourceUrl: 'https://sritgroup.net/nirf/',
    publishedDate: '2025',
    lastVerified: '2026-09-01',
  },
];

export const initialKnowledge: KnowledgeItem[] = [
  {
    id: 'k-college-1',
    title: 'About Shri Ram Institute of Technology (SRIT)',
    category: 'College',
    subcategory: 'Overview',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/shri-ram-group/about-us/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'Shri Ram Institute of Technology (SRIT) is one of the premier engineering and professional educational institutions in Jabalpur, Madhya Pradesh. Founded under the aegis of the Shri Ram Group, the institute provides quality higher education in engineering, technology, computer applications, and management. SRIT is approved by the All India Council for Technical Education (AICTE), New Delhi, and is affiliated with Rajiv Gandhi Proudyogiki Vishwavidyalaya (RGPV), Bhopal for engineering programs, and Rani Durgavati Vishwavidyalaya (RDVV), Jabalpur for management and computer applications.',
  },
  {
    id: 'k-college-history',
    title: 'History & Establishment of Shri Ram Group and SRIT',
    category: 'College',
    subcategory: 'History',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/shri-ram-group/about-us/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'Shri Ram Group officially came into existence on 9 July 2001. Shri Ram Institute of Technology (SRIT) was established in 2001 as its pioneer engineering institution in Jabalpur, under the academic leadership of space scientist Dr. S. P. Kosta (former Deputy Director of ISRO Aryabhata project). Over two decades, the group expanded into a premier multi-disciplinary campus with institutions in Engineering (SRIT, SRIST), Pharmacy (SRIP), MCA, and Management.',
  },
  {
    id: 'k-college-founder-owner',
    title: 'Founder, Ownership & Governance of SRIT',
    category: 'Leadership',
    subcategory: 'Governance',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/shri-ram-group/governing-body/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'The official website states that Shri Ram Group came into existence on 9 July 2001 and identifies Dr. S. P. Kosta as its Group Director / Director General leading the academic vision of the group. The institute is governed by its officially appointed Governing Body and Board of Governors in accordance with AICTE and RGPV regulatory guidelines. Official sources document administrative leadership (Group Director Dr. S. P. Kosta, Principal Dr. Shailesh Gupta, and Chairman/Governing Body), but do not publicly designate a private individual as legal personal "owner".',
  },
  {
    id: 'k-college-2',
    title: 'SRIT Location & Campus Address',
    category: 'College',
    subcategory: 'Location',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'SRIT is located at Near I.T.I, Madhotal, Jabalpur, Madhya Pradesh - 482002, India. The campus is well-connected to Jabalpur Railway Station (approx. 8 km) and Jabalpur Airport (approx. 20 km), with dedicated college bus transit routes across the city.',
  },
  {
    id: 'k-academics-1',
    title: 'Courses & Programs Available at SRIT',
    category: 'Academics',
    subcategory: 'Degree Programs',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/shri-ram-institute-of-technology-srit/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'SRIT offers undergraduate, postgraduate, and diploma degrees: 1. Bachelor of Technology (B.Tech) - 4-year degree in CSE, CSE-AIML, CSE-Data Science, ECE, EE, Mechanical, and Civil. 2. Master of Technology (M.Tech) in CSE and Digital Communication. 3. Master of Computer Applications (MCA) - 2-year software degree. 4. Master of Business Administration (MBA) - 2-year management degree.',
  },
  {
    id: 'k-academics-2',
    title: 'B.Tech Branches at SRIT',
    category: 'Academics',
    subcategory: 'B.Tech Specializations',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/course/bachelor-of-technology-b-tech/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'The B.Tech program offers specialization across major engineering disciplines: 1. Computer Science & Engineering (CSE) 2. Computer Science & Engineering - Artificial Intelligence & Machine Learning (CSE - AI & ML) 3. Computer Science & Engineering - Data Science (CSE - DS) 4. Electronics & Communication Engineering (ECE) 5. Electrical Engineering (EE) 6. Mechanical Engineering (ME) 7. Civil Engineering (CE). All engineering programs follow the RGPV curriculum enriched with practical lab sessions, industry projects, and emerging technology electives.',
  },
  {
    id: 'k-admissions-1',
    title: 'Admission Process & Eligibility',
    category: 'Admissions',
    subcategory: 'Criteria',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'Admissions to B.Tech are conducted primarily through the MP DTE (Directorate of Technical Education, Madhya Pradesh) centralized online counseling, based on JEE Main scores and 10+2 qualifying marks (minimum 45% aggregate in Physics, Mathematics, and Chemistry/Computer Science/Biology for General category, and 40% for reserved categories). Direct college-level counseling (CLC) is also conducted as per DTE guidelines for vacant seats. Candidates for MCA require a recognized Bachelor degree with Mathematics at 10+2 or graduation level.',
  },
  {
    id: 'k-services-1',
    title: 'Student Helpline & Official Contact Information',
    category: 'Student Services',
    subcategory: 'Contact & Support',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'Official College Contacts: Phone Helplines: +91 9755042292, +91 9755042293, 0761-4001933 / 36. Email: info@sritgroup.net. Campus Address: Shri Ram Institute of Technology, Near I.T.I, Madhotal, Jabalpur (M.P.) - 482002. Student support offices include the Academic Section, Examination Cell, Training & Placement Cell, and Student Grievance Redressal Committee.',
  },
  {
    id: 'k-facilities-1',
    title: 'Campus Infrastructure & Facilities',
    category: 'Facilities',
    subcategory: 'Infrastructure',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/shri-ram-group/infrastructure/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'SRIT features a sprawling 30+ acre green campus with state-of-the-art facilities: 1. Central Library with more than 50,000 books, national & international journals, DELNET access, and digital library e-resources. 2. High-tech Computer Centers equipped with high-speed internet, modern workstations, and licensed software. 3. Well-equipped Departmental Laboratories & Mechanical Workshops. 4. Large Multi-purpose Auditorium and air-conditioned Seminar Halls with modern audio-visual systems. 5. College Canteen and cafeteria serving hygienic food and refreshments. 6. Fleet of 50+ college buses connecting all corners of Jabalpur and nearby regions. 7. Medical room with first-aid and visiting doctor. 8. Wi-Fi enabled academic blocks.',
  },
  {
    id: 'k-facilities-2',
    title: 'Sports Facilities & Athletic Complex',
    category: 'Facilities',
    subcategory: 'Sports',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'SRIT provides extensive sports facilities encouraging physical fitness and teamwork: dedicated Cricket ground (host to the renowned Engineering Premier League - EPL), Football field, Volleyball courts, Basketball court, Badminton courts, and indoor sports facilities including Table Tennis, Chess, and Carrom. Annual sports meets and inter-collegiate tournaments are held regularly.',
  },
  {
    id: 'k-clubs-epl',
    title: 'Engineering Premier League (EPL) - Cricket Tournament',
    category: 'Clubs',
    subcategory: 'Sports Activity',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'EPL stands for Engineering Premier League. It is the premier annual cricket tournament hosted by Shri Ram Institute of Technology (SRIT) in Jabalpur. The tournament brings together B.Tech/B.E., M.Tech, and professional students from various engineering branches and colleges across the Mahakoshal region. It features professional cricket pitches, umpire officiating, trophies, player-of-the-match awards, and enthusiastic student participation.',
  },
  {
    id: 'k-clubs-occulus',
    title: 'Occulus - SRIT Rock Band & Music Society',
    category: 'Clubs',
    subcategory: 'Music & Culture',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'Occulus is the official Battle of Rock Bands and music society of Shri Ram Institute of Technology (SRIT) Jabalpur. Founded and run by enthusiastic student musicians, Occulus provides a platform for vocalists, guitarists, drummers, and keyboardists to perform and collaborate. The Occulus band performs live during college fests, sports inaugurations, NCC parades, and inter-collegiate cultural festivals.',
  },
  {
    id: 'k-clubs-vahini',
    title: 'Vahini - Women Empowerment Forum',
    category: 'Clubs',
    subcategory: 'Social Initiative',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'Vahini is the dedicated Women Empowerment Initiative launched by Shri Ram Institute of Technology under the mentorship of senior faculty including Mrs. Mona Jain. Vahini unites female students, faculty members, and staff to promote gender sensitization, leadership, self-defense workshops, health awareness drives, career mentorship, and social outreach for underprivileged girl children.',
  },
  {
    id: 'k-clubs-dance',
    title: 'Dance Club (SRIT Rhythm)',
    category: 'Clubs',
    subcategory: 'Cultural',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'The Dance Club at SRIT coordinates dance enthusiasts across Classical, Western, Contemporary, Hip-Hop, and Folk styles. Members rehearse regularly and represent SRIT at university youth festivals, annual social gatherings, and state-level dance battles.',
  },
  {
    id: 'k-placements-1',
    title: 'Training & Placement Cell (T&P) Activities',
    category: 'Placements',
    subcategory: 'Career Support',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'The Training and Placement (T&P) Cell at SRIT works actively to prepare students for campus recruitment under TPO Dr. Vivek Rajput. T&P activities include: 1. Quantitative aptitude, logical reasoning, and verbal ability training. 2. Technical mock interviews and coding assessments. 3. Soft skills and group discussion grooming sessions. 4. Campus recruitment drives by leading IT and core engineering companies. 5. Industry interaction, expert lectures, and summer internship coordination.',
  },
  {
    id: 'k-firstyear-1',
    title: 'Activities for First-Year Students',
    category: 'Activities',
    subcategory: 'Freshers',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'First-year students at SRIT (including B.Tech AIML, CSE, DS, and other branches) can participate in a wide array of activities: 1. Join student clubs such as Occulus (Music), Dance Club, Sports Club, and Vahini. 2. Participate in the annual EPL Cricket tournament trials and sports meets. 3. Attend technical coding bootcamps, AI/ML workshops, and robotics demonstrations. 4. Compete in TechFest events (quiz, paper presentation, coding competitions). 5. Take part in National Service Scheme (NSS), blood donation camps, and campus green drives.',
  },
  {
    id: 'k-aiml-1',
    title: 'AIML Student Guide & Opportunities at SRIT',
    category: 'Academics',
    subcategory: 'AI & ML Opportunities',
    sourceType: 'Official Website',
    sourceUrl: 'https://sritgroup.net/course/bachelor-of-technology-b-tech/',
    status: 'Published',
    published: true,
    createdBy: 'System (Official Website)',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    content:
      'For B.Tech students specializing in Artificial Intelligence & Machine Learning (AIML): SRIT provides dedicated AI/ML computing labs with GPU acceleration, Python & Data Science environments, and machine learning toolkits. AIML students are encouraged to participate in coding hackathons, the Technical Club, AI project exhibitions at TechFest, and T&P technical upskilling workshops.',
  },
];

export const initialClubs: Club[] = [
  {
    id: 'club-epl',
    name: 'EPL (Engineering Premier League)',
    category: 'Sports',
    description:
      'The premier cricket championship of SRIT Jabalpur, organizing college-level and inter-collegiate leather-ball and tennis-ball cricket tournaments with commentary, live scoring, and awards.',
    activities: [
      'Annual EPL Cricket Tournament',
      'Inter-branch cricket league',
      'Net practice sessions',
      'Selection trials for SRIT College Team',
    ],
    eligibility: 'Open to all registered SRIT students across all branches and years.',
    meetingInformation: 'SRIT Sports Complex / Cricket Pavilion, practice on weekdays 4:30 PM.',
    contactPerson: 'Sports Officer / Faculty Coordinator, Physical Education Dept.',
    contactEmail: 'sports@sritgroup.net',
    contactPhone: '9755042292',
    source: 'Official SRIT Website',
    published: true,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'club-occulus',
    name: 'Occulus (SRIT Rock Band & Music Society)',
    category: 'Cultural / Music',
    description:
      'Official student rock band and music collective of SRIT Jabalpur. Platform for vocalists, instrumentalists, and composers to express musical creativity and perform at major events.',
    activities: [
      'Battle of Rock Bands',
      'Live music concerts at annual fests',
      'Jam sessions & band rehearsals',
      'Acoustic and instrumental showcases',
    ],
    eligibility: 'Open to all music enthusiasts, instrumentalists, and vocalists.',
    meetingInformation: 'Auditorium Music Rehearsal Room, Tuesdays & Fridays 4:00 PM.',
    contactPerson: 'Student Band President & Cultural Committee Faculty',
    contactEmail: 'cultural@sritgroup.net',
    contactPhone: '9755042293',
    source: 'Official SRIT Website',
    published: true,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'club-vahini',
    name: 'Vahini (Women Empowerment Forum)',
    category: 'Social / Empowerment',
    description:
      'A pioneering women empowerment forum at SRIT founded to unite female students, staff, and faculty for leadership development, self-defense training, health awareness, and girl child support.',
    activities: [
      'Self-defense and safety training workshops',
      'Women leadership talks & career guidance',
      'Health, hygiene, and wellness seminars',
      'Social outreach and girl child education support',
    ],
    eligibility: 'Open to all female students and faculty across all SRIT departments.',
    meetingInformation: 'Seminar Hall 1 / Meeting Room, monthly assemblies.',
    contactPerson: 'Mrs. Mona Jain, Assistant Professor & Faculty Convener',
    contactEmail: 'vahini@sritgroup.net',
    contactPhone: '0761-4001933',
    source: 'Official SRIT Website',
    published: true,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'club-dance',
    name: 'SRIT Rhythm (Dance Club)',
    category: 'Cultural',
    description:
      'The official dance troupe of SRIT representing the college in classical, contemporary, western, and folk dance forms across university youth fests and annual college celebrations.',
    activities: [
      'Choreography workshops',
      'Annual fest performances',
      'Inter-college dance competitions',
      'Flash mobs and cultural showcases',
    ],
    eligibility: 'Open to all SRIT students passionate about dancing.',
    meetingInformation: 'Amphitheatre / Dance Studio, Mon & Thu 4:30 PM.',
    contactPerson: 'Cultural Secretary',
    contactEmail: 'dance@sritgroup.net',
    contactPhone: '9755042292',
    source: 'Official SRIT Website',
    published: true,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'club-sports',
    name: 'SRIT Sports Council',
    category: 'Sports',
    description:
      'Coordinates inter-branch and state-level sports competitions in football, basketball, volleyball, badminton, athletics, chess, and table tennis.',
    activities: [
      'Annual Sports Meet',
      'Inter-branch volleyball and football league',
      'Indoor chess & carrom championships',
      'Athletic trials',
    ],
    eligibility: 'Open to all SRIT students.',
    meetingInformation: 'Sports Complex Office, daily 4:00 PM.',
    contactPerson: 'Director of Physical Education',
    contactEmail: 'sports@sritgroup.net',
    contactPhone: '0761-4001936',
    source: 'Official SRIT Website',
    published: true,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'club-tech',
    name: 'SRIT Tech Innovators & Coding Club',
    category: 'Technical',
    description:
      'Student technical community fostering competitive programming, web development, cloud computing, and AI/ML project collaborations.',
    activities: [
      'Weekly coding sprints and DSA problem solving',
      'Hands-on hackathons and project builds',
      'Guest lectures by tech industry alumni',
      'Open-source contribution workshops',
    ],
    eligibility: 'Open to all engineering and computer application students.',
    meetingInformation: 'CS Lab 3, every Saturday 2:00 PM.',
    contactPerson: 'Technical Club Coordinator',
    contactEmail: 'techclub@sritgroup.net',
    contactPhone: '9755042292',
    source: 'Official SRIT Website',
    published: true,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
];

export const initialEvents: CollegeEvent[] = [
  {
    id: 'event-techfest-2026',
    eventName: 'TECHFEST 2026',
    eventType: 'Technical Fest',
    description:
      'SRIT’s grand annual technical extravaganza featuring robotics arenas, coding hackathons, project exhibitions, technical paper presentations, and tech quizzes with awards and certificates.',
    date: '2026-11-14',
    startTime: '10:00 AM',
    endTime: '05:00 PM',
    venue: 'Main Auditorium & Engineering Blocks',
    organizer: 'Shri Ram Institute of Technology',
    department: 'All Engineering Departments',
    eligibility: 'Open to all SRIT students & invited engineering institutions.',
    registrationUrl: 'https://sritgroup.net/events/techfest-2026',
    registrationDeadline: '2026-11-10',
    contactPerson: 'Dr. TechFest Convener',
    contactPhone: '9755042292',
    contactEmail: 'techfest@sritgroup.net',
    status: 'Published',
    year: 2026,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
    publishedBy: 'SRIT Administration',
  },
  {
    id: 'event-epl-2026',
    eventName: 'EPL 2026 - Engineering Premier League',
    eventType: 'Sports Tournament',
    description:
      'The prestigious annual inter-branch cricket tournament of SRIT. Witness fierce athletic competition as branches battle for the coveted EPL Cricket Trophy on SRIT grounds.',
    date: '2026-10-24',
    startTime: '09:00 AM',
    endTime: '06:00 PM',
    venue: 'SRIT Main Sports Grounds',
    organizer: 'Department of Physical Education & Sports',
    department: 'Sports',
    eligibility: 'B.Tech, M.Tech, MCA & MBA branch teams (SRIT students).',
    registrationUrl: 'https://sritgroup.net/sports/epl-2026',
    registrationDeadline: '2026-10-18',
    contactPerson: 'Prof. Sports Coordinator',
    contactPhone: '9755042293',
    contactEmail: 'sports@sritgroup.net',
    status: 'Published',
    year: 2026,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
    publishedBy: 'SRIT Sports Office',
  },
  {
    id: 'event-occulus-2026',
    eventName: 'Occulus Battle of the Bands 2026',
    eventType: 'Cultural Music Fest',
    description:
      'High-voltage live rock and fusion music competition organized by the Occulus Music Society. Electrifying student performances, rhythm duels, and acoustic sessions.',
    date: '2026-11-05',
    startTime: '05:00 PM',
    endTime: '09:30 PM',
    venue: 'Open Air Amphitheatre',
    organizer: 'Occulus Society & Cultural Committee',
    department: 'Cultural Affairs',
    eligibility: 'All college bands and student solo artists.',
    registrationUrl: 'https://sritgroup.net/cultural/occulus-2026',
    registrationDeadline: '2026-10-31',
    contactPerson: 'Occulus Student Band Lead',
    contactPhone: '0761-4001933',
    contactEmail: 'cultural@sritgroup.net',
    status: 'Published',
    year: 2026,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
    publishedBy: 'Cultural Committee',
  },
  {
    id: 'event-robotics-2026',
    eventName: 'National Science & Robotics Expo 2026',
    eventType: 'Workshop & Exhibition',
    description:
      'Hands-on robotics exhibition showcasing line-follower bots, drone demonstrations, IoT embedded systems, and automation projects built by SRIT students.',
    date: '2026-10-28',
    startTime: '10:00 AM',
    endTime: '04:00 PM',
    venue: 'Central Engineering Laboratories',
    organizer: 'ECE & Mechanical Departments',
    department: 'ECE',
    eligibility: 'Open to all engineering students.',
    registrationUrl: 'https://sritgroup.net/events/robotics-expo',
    registrationDeadline: '2026-10-25',
    contactPerson: 'Faculty Coordinator - Robotics',
    contactPhone: '9755042292',
    contactEmail: 'robotics@sritgroup.net',
    status: 'Published',
    year: 2026,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
    publishedBy: 'ECE Dept',
  },
  {
    id: 'event-vahini-2026',
    eventName: 'Vahini Women Leadership & Empowerment Conclave',
    eventType: 'Seminar & Workshop',
    description:
      'Special conclave featuring guest lectures by accomplished women leaders, interactive self-defense demonstration, and awards recognizing female student achievers.',
    date: '2026-11-08',
    startTime: '11:00 AM',
    endTime: '02:00 PM',
    venue: 'Seminar Hall 1',
    organizer: 'Vahini Forum',
    department: 'Student Affairs',
    eligibility: 'All students and faculty members welcome.',
    registrationUrl: 'https://sritgroup.net/vahini/conclave-2026',
    registrationDeadline: '2026-11-06',
    contactPerson: 'Mrs. Mona Jain',
    contactPhone: '0761-4001933',
    contactEmail: 'vahini@sritgroup.net',
    status: 'Published',
    year: 2026,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
    publishedBy: 'Vahini Cell',
  },
  {
    id: 'event-placement-bootcamp',
    eventName: 'Campus Placement Preparation Bootcamp',
    eventType: 'Training Workshop',
    description:
      'Intensive training covering coding rounds, technical interviews, company-specific aptitude shortcuts, and mock HR interviews by corporate trainers.',
    date: '2026-10-18',
    startTime: '02:00 PM',
    endTime: '05:30 PM',
    venue: 'T&P Seminar Hall & Computer Labs',
    organizer: 'Training & Placement Cell',
    department: 'T&P',
    eligibility: '3rd year and 4th year B.Tech & MCA students.',
    registrationUrl: 'https://sritgroup.net/placements/bootcamp',
    registrationDeadline: '2026-10-16',
    contactPerson: 'Dr. Vivek Rajput, Head - Training & Placement',
    contactPhone: '9755042292',
    contactEmail: 'placement@sritgroup.net',
    status: 'Published',
    year: 2026,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
    publishedBy: 'T&P Cell',
  },
  {
    id: 'event-induction-2026',
    eventName: 'Orientation & Induction Day 2026',
    eventType: 'College Celebration',
    description:
      'Official welcome address by Principal, HODs, campus tour, and introductory sessions for the incoming batch of 2026.',
    date: '2026-09-15',
    startTime: '10:00 AM',
    endTime: '03:00 PM',
    venue: 'Main Auditorium',
    organizer: 'Academic Committee',
    department: 'All',
    eligibility: 'First-year students and parents.',
    registrationUrl: 'https://sritgroup.net',
    status: 'Completed',
    year: 2026,
    createdAt: '2026-08-20T00:00:00.000Z',
    updatedAt: '2026-09-15T18:00:00.000Z',
    publishedBy: 'Administration',
  },
];
